# Generated by Django 4.2.dev20220803094251 on 2022-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicat', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
