# Generated by Django 4.2.dev20220803094251 on 2022-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicat', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ccn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicat', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicat', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Indicateur',
        ),
    ]
