# Generated by Django 4.2.dev20220803094251 on 2022-08-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auxiliaire_ccn_fusion_delete_indicateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KPI_secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=300)),
                ('unite', models.CharField(max_length=300)),
                ('secteur', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('indicateur_perfor', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Auxiliaire',
        ),
        migrations.DeleteModel(
            name='Ccn',
        ),
        migrations.DeleteModel(
            name='Fusion',
        ),
        migrations.AddField(
            model_name='data',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kpi_secteur'),
        ),
    ]
